// Opções compartilhadas para os selects
export const CONVENIO_OPTIONS = [
  { value: '', label: 'Selecione...' },
  { value: 'PARTICULAR', label: 'PARTICULAR' },
  { value: 'SULAMERICA', label: 'SULAMERICA' },
  { value: 'BRADESCO', label: 'BRADESCO' },
  { value: 'ABET', label: 'ABET' },
  { value: 'ALLIANZ', label: 'ALLIANZ' },
  { value: 'AMEPLAN', label: 'AMEPLAN' },
  { value: 'AMIL', label: 'AMIL' },
  { value: 'AMAFRESP', label: 'AMAFRESP' },
  { value: 'CABESP', label: 'CABESP' },
  { value: 'CARE PLUS', label: 'CARE PLUS' },
  { value: 'CASSI', label: 'CASSI' },
  { value: 'CET', label: 'CET' },
  { value: 'CLASSES LABORIOSAS', label: 'CLASSES LABORIOSAS' },
  { value: 'CUIDAR ME', label: 'CUIDAR ME' },
  { value: 'ECONOMUS', label: 'ECONOMUS' },
  { value: 'EMBRATEL', label: 'EMBRATEL' },
  { value: 'FUNDACAO CESP', label: 'FUNDACAO CESP' },
  { value: 'GAMA', label: 'GAMA' },
  { value: 'GEAP', label: 'GEAP' },
  { value: 'GOLDEN CROSS', label: 'GOLDEN CROSS' },
  { value: 'GREEN LINE', label: 'GREEN LINE' },
  { value: 'INTERMEDICA', label: 'INTERMEDICA' },
  { value: 'ITAU', label: 'ITAU' },
  { value: 'NOTRE DAME', label: 'NOTRE DAME' },
  { value: 'MARITIMA', label: 'MARITIMA' },
  { value: 'MEDIAL', label: 'MEDIAL' },
  { value: 'MEDISERVICE', label: 'MEDISERVICE' },
  { value: 'METRUS', label: 'METRUS' },
  { value: 'OMINT', label: 'OMINT' },
  { value: 'ONE HEALTH', label: 'ONE HEALTH' },
  { value: 'PORTO SEGURO', label: 'PORTO SEGURO' },
  { value: 'POSTAL SAUDE', label: 'POSTAL SAUDE' },
  { value: 'SABESPREV', label: 'SABESPREV' },
  { value: 'SAUDE CAIXA', label: 'SAUDE CAIXA' },
  { value: 'SOMPO SAÚDE', label: 'SOMPO SAÚDE' },
  { value: 'TRASMONTANO', label: 'TRASMONTANO' },
  { value: 'UNIMED', label: 'UNIMED' },
  { value: 'UNIMED CENTRAL NACIONAL', label: 'UNIMED CENTRAL NACIONAL' },
  { value: 'UNIMED FESP', label: 'UNIMED FESP' },
  { value: 'UNIMED GUARULHOS', label: 'UNIMED GUARULHOS' },
  { value: 'UNIMED SEGUROS', label: 'UNIMED SEGUROS' },
  { value: 'VOLKSWAGEN', label: 'VOLKSWAGEN' },
  { value: 'OUTROS', label: 'OUTROS' },
];

// Subtipo tem muitas opções - permitir input livre por enquanto
export const SUBTIPO_OPTIONS = [
  { value: '', label: 'Selecione ou digite...' },
];
